//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnus
    {
        public int SSN { get; set; }
        public string Nane { get; set; }
        public string EmployerNameAddress { get; set; }
        public string CurrentPosition { get; set; }
        public string CurrentSalary { get; set; }
        public float GPA { get; set; }
        public int School_ID { get; set; }
    
        public virtual School School { get; set; }
    }
}
