//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int Curriculum_Code { get; set; }
        public string Name { get; set; }
        public string List_OF_Courses { get; set; }
        public Nullable<int> Course_Code { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
